import { ipcMain } from "electron";
import { addStates } from "./countries/addStates.js";
import { createCountry } from "./countries/createCountry.js";
import { deleteCountry } from "./countries/deleteCountry.js";
import { getAllCountries } from "./countries/getAllCountries.js";
import { removeStates } from "./countries/removeStates.js";
import { updateCountry } from "./countries/updateCountry.js";
import { createEthnicity } from "./ethnicities/createEthnicity.js";
import { deleteEthnicity } from "./ethnicities/deleteEthnicity.js";
import { getAllEthnicities } from "./ethnicities/getAllEthnicities.js";
import { renameEthnicity } from "./ethnicities/renameEthnicity.js";
import { loadMapImage } from "./mapImage/loadMapImage.js";
import { saveMapImage } from "./mapImage/saveMapImage.js";
import { createMap } from "./maps/createMap.js";
import { deleteMap } from "./maps/deleteMap.js";
import { getMaps } from "./maps/getMaps.js";
import { renameMap } from "./maps/renameMap.js";
import { addPopulation } from "./provinces/addPopulation.js";
import { changeProvinceType } from "./provinces/changeProvinceType.js";
import { extractProvinceShapes } from "./provinces/extractProvinceShapes.js";
import { getAllProvinces } from "./provinces/getAllProvinces.js";
import { getProvinceByColor } from "./provinces/getProvinceByColor.js";
import { getProvinceById } from "./provinces/getProvinceById.js";
import { addProvinces } from "./states/addProvinces.js";
import { createState } from "./states/createState.js";
import { deleteState } from "./states/deleteState.js";
import { getAllStates } from "./states/getAllStates.js";
import { getStateByProvinceId } from "./states/getStateByProvinceId.js";
import { removeProvinces } from "./states/removeProvinces.js";
import { renameState } from "./states/renameState.js";

export const setupHandlers = () => {
    ipcMain.handle("saveMapImage", saveMapImage);
    ipcMain.handle("loadMapImage", loadMapImage);
    ipcMain.handle("getMaps", getMaps);
    ipcMain.handle("createMap", createMap);
    ipcMain.handle("deleteMap", deleteMap);
    ipcMain.handle("renameMap", renameMap);
    ipcMain.handle("getAllProvinces", getAllProvinces);
    ipcMain.handle("getProvinceByColor", getProvinceByColor);
    ipcMain.handle("getProvinceById", getProvinceById);
    ipcMain.handle("extractProvinceShapes", extractProvinceShapes);
    ipcMain.handle("changeProvinceType", changeProvinceType);
    ipcMain.handle("getStateByProvinceId", getStateByProvinceId);
    ipcMain.handle("getAllStates", getAllStates);
    ipcMain.handle("createState", createState);
    ipcMain.handle("addProvinces", addProvinces);
    ipcMain.handle("removeProvinces", removeProvinces);
    ipcMain.handle("renameState", renameState);
    ipcMain.handle("deleteState", deleteState);
    ipcMain.handle("createCountry", createCountry);
    ipcMain.handle("deleteCountry", deleteCountry);
    ipcMain.handle("getAllCountries", getAllCountries);
    ipcMain.handle("addStates", addStates);
    ipcMain.handle("removeStates", removeStates);
    ipcMain.handle("updateCountry", updateCountry);
    ipcMain.handle("getAllEthnicities", getAllEthnicities);
    ipcMain.handle("deleteEthnicity", deleteEthnicity);
    ipcMain.handle("renameEthnicity", renameEthnicity);
    ipcMain.handle("createEthnicity", createEthnicity);
    ipcMain.handle("addPopulation", addPopulation);
};
